### ISSUE TITLE
Add the sample codes from "Groovy in Action" as test cases

### ISSUE THREAD

**Issue by daniellansun** [jespersm/incubator-groovy#10]
Groovy in Action(2nd Edition) is the most definitive book for Groovy programming language. The sample codes from the book covers almost whole Groovy syntax, so when the new parser can handle all of the sample codes properly, it is mature enough to release as a beta version.

``` plain
https://github.com/Dierk/GroovyInAction
```

**Comment by jespersm** [comment]
This is interesting, but we should be very careful with the licensing, to ensure clean Apache IP conformance.

**Comment by daniellansun** [comment]
I agree with you.

**Comment by daniellansun** [comment]
Guillaume replied:
"Dierk told me the source code from Groovy in Action 2nd edition is actually Apache licensed, and can be found here on Github:
https://github.com/Dierk/GroovyInAction

So you can reuse it for the new parser.

Let's be sure to keep the attribution, to remember where this code is coming from.

Guillaume"

**Comment by daniellansun** [comment]
https://github.com/jespersm/groovy/blob/antlr4/subprojects/groovy-antlr4-grammar/src/test/resources/GroovyInAction2/allsources.txt
