### ISSUE TITLE
GString-closure not supported

### ISSUE THREAD

**Issue by jespersm** [jespersm/incubator-groovy#12]
A GString may contain a closure as one of its expressions, written in a particular style, like

`"GString ${ -> heavy() }"`

Example from the console: 

`println "${ -> println "1 - lazy" ; 1 } - ${ println "2 - eager" ; 2 }"
`
Gives error: 

> 1 compilation error:
> 
> no viable alternative at input 'println"${->' at line: 1, column: 13

**Comment by danielsun1106** [comment]
I'm trying to fix it.



在 Jesper Steen Møller <notifications@github.com>，2016年3月21日 20:03写道：

A GString may contain a closure as one of its expressions, written in a particular style, like

"GString ${ -> heavy() }"

Example from the console:

println "${ -> println "1 - lazy" ; 1 } - ${ println "2 - eager" ; 2 }"

Gives error:

1 compilation error:

no viable alternative at input 'println"${->' at line: 1, column: 13

**Comment by daniellansun** [comment]
The statements are not supported in the GString-closure, I'll fix them together.

**Comment by daniellansun** [comment]
The issue is fixed. 
The related PR: https://github.com/jespersm/groovy/pull/14
