### ISSUE TITLE
tuples are not supported in declarations and assignments

### ISSUE THREAD

**Issue by jespersm** [jespersm/incubator-groovy#13]
For example

`def (a, b) = [3, 4]`

gives

> 1 compilation error:
> 
> no viable alternative at input 'def(' at line: 1, column: 5

and
`(c,d) = [5,6]`
gives

> 1 compilation error:
> 
> no viable alternative at input '(c,' at line: 1, column: 3

**Comment by danielsun1106** [comment]
I'll try to fix it.

**Comment by daniellansun** [comment]
The issue is fixed: https://github.com/jespersm/groovy/pull/17
