### ISSUE TITLE
Fail to parse the call expression when the callee is not a path expression

### ISSUE THREAD

**Issue by daniellansun** [jespersm/incubator-groovy#18]
``` groovy
['a','b','c'].inject('x') {
    result, item -> item + result + item
}
```

**Comment by jespersm** [comment]
I'm thinking we should combine the two rules for calls, since "obj.meth(arg) meth arg" is also allowed in Groovy.

I have a stash which "mostly works", I'll examine that.

**Comment by daniellansun** [comment]
Yep. The call expression and method call expression are very similar. Combining the two rules will be good.

**Comment by daniellansun** [comment]
Listing_D_05_GPath.groovy from GinA2 is a good test case for call expression:
 https://github.com/Dierk/GroovyInAction/blob/master/listings/appD/Listing_D_05_GPath.groovy

**Comment by daniellansun** [comment]
@jespersm looking forward to your stashed fix :-)

**Comment by danielsun1106** [comment]
@jespersm looking forward to your stashed fix :-)

**Comment by blackdrag** [comment]
+1 on combining the rules if possible and sensible

**Comment by jespersm** [comment]
It turns out Listing_D_05_GPath failed due to a different bug, which I fixed in d7c5d815f8753b3e3116cb067389e5f746f3ab3c

**Comment by jespersm** [comment]
Also ['a','b','c'].inject('x') {
    result, item -> item + result + item
}

is not really a command call, but a "trailing closure argument" (after a normal argument list "('x')"). That's a separate bug.

**Comment by daniellansun** [comment]
Yep. The related rule alt is call expression. The path expression in the alt can not handle the list contructor.

**Comment by daniellansun** [comment]
Fixed by: https://github.com/jespersm/groovy/commit/4ac81ae115b8e86ae374f6a9c96370780502d1b3
The related test case: https://github.com/jespersm/groovy/commit/00d0957afeabb2bc085619db3de0691ee1092f98
