### ISSUE TITLE
Support lamda expression like Java8

### ISSUE THREAD

**Issue by daniellansun** [jespersm/incubator-groovy#20]
Lamda expression is very similar with closure. We can translate lamda to closure in the ASTBuilder.
The new feature will be added when the new parser can handle current  syntax of Groovy and Groovy dev team approve it.
Reference: http://docs.oracle.com/javase/tutorial/java/javaOO/lambdaexpressions.html#syntax

**Comment by blackdrag** [comment]
parsing the lambda into a ClosureExpression is a good idea. +1

**Comment by daniellansun** [comment]
We can also add some property(e.g. syntheticLamda) for ClosureExpression to indicate that the closure is a lamda expression actually.
