### ISSUE TITLE
Newline handling in multiline strings behaves differently from Antlr2 parser on Windows

### ISSUE THREAD

**Issue by jespersm** [jespersm/incubator-groovy#3]
Newline handling in multiline strings behaves differently from Antlr2 parser on Windows.
MainTest for Literals_Strings_Issue36_3.groovy fails in Windows, but runs fine on Windows, so some kind of newline normalization is either taking place, or NOT taking place, which is different from how it works in the old parser.

**Comment by danielsun1106** [comment]
I've fixed it and I'll push commits later.

**Comment by daniellansun** [comment]
commits pushed: https://github.com/jespersm/groovy/pull/8/commits/3c3338a3938be6ae6cd2ab6abe571d70a47322a3

**Comment by daniellansun** [comment]
one more test case added: https://github.com/jespersm/groovy/commit/62e79f0fd5cf3d29f6912446f8113b8f2982764f
