### ISSUE TITLE
Combine callExpression and methodCallExpression

### ISSUE THREAD

**Issue by daniellansun** [jespersm/incubator-groovy#33]
``` antlr
| pathExpression (LPAREN argumentList? RPAREN)? closureExpressionRule* #callExpression
| expression (DOT | SAFE_DOT | STAR_DOT) (selectorName | STRING | gstring) ((LPAREN argumentList? RPAREN)| argumentList) #methodCallExpression
```

**Comment by daniellansun** [comment]
@jespersm 
Jesper, does your stashed fix work now?

**Comment by jespersm** [comment]
Sadly, my stashed won't apply anymore, but I'm thinking we should eliminate methodCallExpression and just recognize callExpressions as such, and transform the AST from the property expression.

**Comment by daniellansun** [comment]
It does not matter. I'll try to fix it.

**Comment by daniellansun** [comment]
Currently 94% test cases pass. The parenthesis-less syntax make the parser very confused...
I wish I could fix the 6 failed test cases.

**Comment by daniellansun** [comment]
Only one test case failed. I feel that I'm trying to solve Goldbach Conjecture...

**Comment by daniellansun** [comment]
Fixed by: https://github.com/jespersm/groovy/commit/4ac81ae115b8e86ae374f6a9c96370780502d1b3
