### ISSUE TITLE
Support do-while control structure

### ISSUE THREAD

**Issue by daniellansun** [jespersm/incubator-groovy#38]
do-while is a basic control structure, but Groovy does not support it.

@blackdrag Can we support it in the new parser?

**Comment by blackdrag** [comment]
We did not support it due to issues with ambiguity. Afaik "do" is a keyword in the old grammar, so it would be no breaker... I guess we can support it, if it does not cause problems

**Comment by daniellansun** [comment]
OK. I'll try to support it when all the GinA2 test cases pass ;-)
