### ISSUE TITLE
Support full range of Java identifiers

### ISSUE THREAD

**Issue by jespersm** [jespersm/incubator-groovy#4]
Java allows all sorts of Unicode letter classes in identifiers --  this is yet unsupported in the Antlr4 parser

**Comment by daniellansun** [comment]
I created a PR(Allow unicode identifiers #5) to fix it.

**Comment by jespersm** [comment]
I forgot to mention: We need the same for GSTRING_ID and GSTRING_PATH_PART

**Comment by daniellansun** [comment]
GSTRING_ID and GSTRING_PATH_PART support Unicode characters now.

**Comment by jespersm** [comment]
Closed with #5
