### ISSUE TITLE
cmdExpressionRule does not support method call on expression

### ISSUE THREAD

**Issue by daniellansun** [jespersm/incubator-groovy#41]
(1 + 2).plus 3 plus 4

**Comment by blackdrag** [comment]
if the first part is a path expression, it means path expressions don´t support parts being (1+2), right?

**Comment by jespersm** [comment]
Hmm:
"a b" means "this.a(b)" // Command
"a b c" means "a(b).c" // Command with trailing property
"a b c d" means "a(b).c(d)" // Command inv with command inv.
"a.b c d" means "a.b(c).d" // Expression with paren-less argument and trailing property
"a.b c d e" means "a.b(c).d(e)" // Method call expression with paren-less argument followed by command call

So, as I see it, a command expression is EITHER (selector paren-less-arglist)+ (propertySelector)? or expression followed by command expression.
If we separate the command expression as "higher level" expression, only used in declarations initializers , on the right hand side of assignments and in statements, wouldn't that simplify things quite a bit?

**Comment by daniellansun** [comment]
@blackdrag 
Yeah, this is what I mean. And many other expressions does not support, e.g. list, map contructors

**Comment by daniellansun** [comment]
@jespersm cmd expression only used in declarations initializers? I'm not sure...
@blackdrag Could you confirm it for us?

**Comment by daniellansun** [comment]
@jespersm the following code is not used in declarations initializers, but it can be recognized by the old parser. so if cmd expression only being used in declarations initializers will break the compatibility..

```
(1 + 2).plus 3 plus 4
```

**Comment by jespersm** [comment]
I wasn't clear (in the sentence above), since I've missed an Oxford comma. I've rewritten it as bullets:
If we separate the command expression as "higher level" expression, I think it would simplify things quite a bit. Command expressions should be usable in:
- declarations initializers
- on the right hand side of assignments
- as statements

**Comment by blackdrag** [comment]
I think the part with "a b" being equal to this.a(b) is misleading. It does mean that, but with an implicit this. So please see it as having a(b) only instead.

@jespersm Having command expressions only at the places you mentioned is about the old state I think. It would be nice to be able to write a command expression in paras... like (a b c d) at any place, that allows an expression.

**Comment by jespersm** [comment]
@blackdrag: Yes, we'll try those places, but I'd rather ensure that the grammar can be compatible with the current Antlr 2.x version first.

**Comment by daniellansun** [comment]
Fixed by: https://github.com/jespersm/groovy/commit/00c3aafee4e4b1766177d50981f722f9d2863f4f
