### ISSUE TITLE
Make command expression become a real expression

### ISSUE THREAD

**Issue by daniellansun** [jespersm/incubator-groovy#42]
As Jochen said: "It would be nice to be able to write a command expression in paras... like (a b c d) at any place, that allows an expression."

e.g.

``` groovy
(1.plus 2 plus 3) + (2.plus 3 plus 4) // should be supported
```

**Comment by jespersm** [comment]
What to you mean by this? Can you provide an example?

**Comment by blackdrag** [comment]
if you have a DSL `foo bar x` and you want to know what it returns, you currently cannot simply write `println(foo bar x)` for example

**Comment by daniellansun** [comment]
Jochen, command expression in paras... like (a b c d) can be passed into a method, which will be like println((a b c d)).  The outest parentheses belong to method and the inner ones belong to command expression. The extra parentheses are needed due to parenthesis-less call does not support to follow by parentheses. Maybe we can do some magic...

**Comment by daniellansun** [comment]
We can make the parentheses of command expression optional.  As a side effect, it will add some ambiguities to the grammar

**Comment by daniellansun** [comment]
Fixed by the following commits(same with https://github.com/jespersm/groovy/issues/43 ):
https://github.com/jespersm/groovy/commit/637b850c5bc3233f6dc3df52c1d0a8d3fbb19474
https://github.com/jespersm/groovy/commit/46638d68e111ed7eda14e0ece920b470dbf7026c
https://github.com/jespersm/groovy/commit/337350e1b5a4083ec1647796ee92708fe95ca6bc
https://github.com/jespersm/groovy/commit/15860938c4b7b692898d4e355daba39e59286017

**Comment by daniellansun** [comment]
The related test case is here: https://github.com/jespersm/groovy/commit/7c91912fd40173bbc5c10b957675e52e5fa3b42f
