### ISSUE TITLE
Identifier in the gstring can not be recognized properly when mixing special characters

### ISSUE THREAD

**Issue by daniellansun** [jespersm/incubator-groovy#48]
Both the new parser and IntelliJ IDEA 15 recognize `fºF` and `cºC` as identifer, which is not same as the old parser do.

``` groovy
"$scenario: $fºF should convert into $cºC"      // º's unicode is 006F
```

**Comment by jespersm** [comment]
FWIW:

º is Unicode Character 'MASCULINE ORDINAL INDICATOR' (U+00BA) which is really an identifier in Java, and Groovy should recognize this.
° is Unicode Character 'DEGREE SIGN' (U+00B0) which is not an identifier.

U+006F is plain old 'o' (LATIN SMALL LETTER O)

**Comment by daniellansun** [comment]
@jespersm 
It may be a bug of old parser...
@blackdrag 
Could you confirm it for us?

**Comment by blackdrag** [comment]
sounds like a bug to me

**Comment by daniellansun** [comment]
Thanks.
