### ISSUE TITLE
Support call on constants etc.

### ISSUE THREAD

**Issue by daniellansun** [jespersm/incubator-groovy#53]
``` groovy
'm'() + /aa/() + $/bb/$() + "$m"() + /a${'x'}a/() + $/b${'x'}b/$() + 1.2('b') + 1('a') + 2() + null() + true() + false() + a() + {a,b->}(1, 2) + [1, 2]() + [a:1, b:2]() + new int[0]() + new Integer(1)()
```

**Comment by danielsun1106** [comment]
The related test case for call on the result of method call.
```groovy
//FIXME support "someMethod()()"        "grails-plugin-testing/src/main/groovy/grails/test/mixin/webflow/WebFlowUnitTestSupport.groovy" | addIgnore([Parameter, IfStatement, ThrowStatement, ExpressionStatement, ReturnStatement, ForStatement, FieldNode, PropertyNode, MethodNode, GenericsType], ASTComparatorCategory.LOCATION_IGNORE_LIST)
```

**Comment by jespersm** [comment]
We should be able to call on just about anything - remember that whatever we parse could be picked up by AST transformations and totally changed, really.

**Comment by daniellansun** [comment]
OK. 
I split "call on expression" into "call on atom expression such as constant, method call etc." and "call on parenthesis expression".
Currently the latter and call on the result of method and closure call have been supported.

**Comment by daniellansun** [comment]
Fixed by: https://github.com/jespersm/groovy/commit/bbe6edbc315c1f163f740b9ccc8e3d43ec09081b
