### ISSUE TITLE
Support call on built-in type and class name

### ISSUE THREAD

**Issue by daniellansun** [jespersm/incubator-groovy#56]
``` groovy
(int)() + (Integer)() + (java.lang.Integer)()
```

**Comment by jespersm** [comment]
Note how Groovy 2.x in fact parses `(int)()` as `("int")()`, without detecting the type literal.
In fact, the behaviour is the same for `(foo)()` which is parsed as `("foo")()`

I think this is an error in Groovy 2.x. Try

```
def foo = { println "OK" }
foo()
```

That works, but the following does not:

```
def foo = { println "OK" }
(foo)()
```

Quirky: This mirrors how `object.(methodName)()` is parsed as `object.methodName()` where I would have expected it to work like `object."$methodName"()`.
Consider:

```
def methodName = 'length'
"Groovy".(methodName+'')()
```

This tries to find String.methodName()

The following:

```
def methodName = 'length'
"Groovy".(methodName+'')()
```

does the right thing and evaluates `methodName + ''` before invoking.
