### ISSUE TITLE
Add "JavaDoc" as metadata to types and members

### ISSUE THREAD

**Issue by jespersm** [jespersm/incubator-groovy#6]
To make it easier to generate Groovydoc, the parser should collect JavaDoc-style comments and set them as metadata on the relevant AST nodes, as discussed in http://mail-archives.apache.org/mod_mbox/groovy-dev/201603.mbox/%3CCAJ2HCd_dGEDj5tLh5oQ9Bqbv0hfu3y8L%2BqHCumhk9NdFyjaZOA%40mail.gmail.com%3E

**Comment by daniellansun** [comment]
We can achieve it after the antlr4 parser can handle the whole syntax as the antlr2 done.

**Comment by danielsun1106** [comment]
We can achieve it after the antlr4 parser can handle the whole syntax as the antlr2 done.

**Comment by daniellansun** [comment]
As nodeMetaData is not the content to compare, so I achieve it now.
The related commit: https://github.com/jespersm/groovy/commit/ce35fbbdbff1711b8bb253b2d201715e92e609fb
