### ISSUE TITLE
Proper unescaping of string literals

### ISSUE THREAD

**Issue by jespersm** [jespersm/incubator-groovy#7]
String literals are not correctly unescaped by the scanner or ASTBuilder.

**Comment by danielsun1106** [comment]
I'm investigating the issue.

**Comment by daniellansun** [comment]
commits pushed: https://github.com/jespersm/groovy/pull/8/commits/c43b9a43e816669c42646e57713271ef567bfd82

**Comment by daniellansun** [comment]
more commits pushed: https://github.com/jespersm/groovy/pull/8/commits/3a8e63748c859456ae42931a76dba96828314422

**Comment by jespersm** [comment]
Is this complete now, then?

**Comment by daniellansun** [comment]
Currently unicode escapes, standard escapes and octal escapes can be unescaped properly, so I think the issue is fixed.

在 Jesper Steen Møller notifications@github.com，2016年3月21日 08:36写道：

Is this complete now, then?

**Comment by daniellansun** [comment]
Any more test cases should be covered?
